# Generated by Django 6.0.2 on 2026-02-20 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('youtube_publish', 'YouTube (Publish)'), ('soundcloud', 'SoundCloud'), ('spotify', 'Spotify'), ('deezer', 'Deezer'), ('local', 'Local Disk'), ('ftp', 'FTP Server')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('credentials_data', models.BinaryField(blank=True, null=True)),
                ('config', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'source_connections',
                'ordering': ['source_type', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='YouTubeCredential',
        ),
    ]
