# Generated by Django 6.0.2 on 2026-02-20 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sourceconnection_delete_youtubecredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingjob',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='api.sourceconnection'),
        ),
    ]
