# Generated by Django 6.0.2 on 2026-02-21 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pendingjob_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=200)),
                ('playlist_name', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('ready', 'Ready to upload'), ('syncing', 'Uploading'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs_from', to='api.sourceconnection')),
                ('source_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs_to', to='api.sourceconnection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sync_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_track_id', models.CharField(max_length=200)),
                ('source_title', models.CharField(max_length=400)),
                ('source_artist', models.CharField(blank=True, max_length=200)),
                ('source_duration_ms', models.IntegerField(blank=True, null=True)),
                ('source_artwork_url', models.URLField(blank=True, max_length=500)),
                ('source_permalink_url', models.URLField(blank=True, max_length=500)),
                ('match_confidence', models.FloatField(blank=True, null=True)),
                ('target_video_id', models.CharField(blank=True, max_length=100)),
                ('target_title', models.CharField(blank=True, max_length=400)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('uncertain', 'Uncertain'), ('not_found', 'Not found'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('skipped', 'Skipped'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('position', models.IntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='api.syncjob')),
            ],
            options={
                'db_table': 'sync_tracks',
                'ordering': ['position'],
            },
        ),
    ]
