# Generated by Django 6.0.2 on 2026-02-22 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_trackfingerprint'),
        ('api', '0004_syncjob_synctrack'),
    ]

    operations = [
    ]
