# Generated by Django 6.0.2 on 2026-02-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_shazam_and_local_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synctrack',
            name='target_video_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
