# Generated by Django 6.0.2 on 2026-02-27 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_synctrack_target_video_id_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncjob',
            name='error_message',
            field=models.TextField(blank=True),
        ),
    ]
