# Generated by Django 6.0.2 on 2026-03-11 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_sync_job_error_message'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Soundlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('auto_sync_enabled', models.BooleanField(default=False)),
                ('auto_sync_interval_minutes', models.IntegerField(default=0)),
                ('last_auto_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soundlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'soundlists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SoundlistMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=200)),
                ('playlist_name_cache', models.CharField(blank=True, max_length=300)),
                ('role', models.CharField(choices=[('source_only', 'Source only'), ('target_only', 'Target only'), ('bidirectional', 'Bidirectional')], default='bidirectional', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('soundlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.soundlist')),
                ('source_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soundlist_members', to='api.sourceconnection')),
            ],
            options={
                'db_table': 'soundlist_members',
                'unique_together': {('soundlist', 'source_connection', 'playlist_id')},
            },
        ),
        migrations.CreateModel(
            name='SoundlistSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('cron', 'Cron')], default='manual', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('soundlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_runs', to='api.soundlist')),
            ],
            options={
                'db_table': 'soundlist_sync_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SoundlistSyncItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_identifier', models.CharField(max_length=500)),
                ('action', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove'), ('noop', 'No-op'), ('conflict', 'Conflict')], max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_items', to='api.soundlistmember')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.soundlistsyncrun')),
            ],
            options={
                'db_table': 'soundlist_sync_items',
            },
        ),
    ]
