# Generated by Django 6.0.2 on 2026-03-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_soundlists'),
    ]

    operations = [
        migrations.AddField(
            model_name='soundlistsyncrun',
            name='progress',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
