# Generated by Django 6.0.2 on 2026-03-12 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_soundlist_sync_run_progress'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundlistMatchCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_platform', models.CharField(max_length=20)),
                ('source_track_id', models.CharField(max_length=500)),
                ('source_title', models.CharField(max_length=400)),
                ('source_artist', models.CharField(blank=True, max_length=200)),
                ('source_duration_ms', models.IntegerField(blank=True, null=True)),
                ('target_platform', models.CharField(blank=True, max_length=20)),
                ('target_track_id', models.CharField(blank=True, max_length=500)),
                ('target_title', models.CharField(blank=True, max_length=400)),
                ('match_confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('uncertain', 'Uncertain'), ('not_found', 'Not found'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('user_feedback', models.CharField(blank=True, max_length=20)),
                ('alternatives', models.JSONField(blank=True, default=list)),
                ('rejected_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('soundlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_candidates', to='api.soundlist')),
                ('source_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.soundlistmember')),
                ('target_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.soundlistmember')),
            ],
            options={
                'db_table': 'soundlist_match_candidates',
                'unique_together': {('soundlist', 'source_track_id', 'source_platform', 'target_member')},
            },
        ),
    ]
