# Generated by Django 6.0.2

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_remove_soundlists'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MirrorSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('auto_sync_enabled', models.BooleanField(default=False)),
                ('auto_sync_interval_minutes', models.IntegerField(default=0)),
                ('last_auto_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mirror_syncs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mirror_syncs',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MirrorSyncMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(max_length=200)),
                ('playlist_name', models.CharField(blank=True, max_length=300)),
                ('role', models.CharField(choices=[('bidirectional', 'Bidirectional'), ('source_only', 'Source only'), ('target_only', 'Target only')], default='bidirectional', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('mirror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='api.mirrorsync')),
                ('source_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mirror_members', to='api.sourceconnection')),
            ],
            options={
                'db_table': 'mirror_sync_members',
                'unique_together': {('mirror', 'source_connection', 'playlist_id')},
            },
        ),
        migrations.CreateModel(
            name='MirrorMatchCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_platform', models.CharField(max_length=20)),
                ('source_track_id', models.CharField(max_length=500)),
                ('source_title', models.CharField(max_length=400)),
                ('source_artist', models.CharField(blank=True, max_length=200)),
                ('source_duration_ms', models.IntegerField(blank=True, null=True)),
                ('target_platform', models.CharField(blank=True, max_length=20)),
                ('target_track_id', models.CharField(blank=True, max_length=500)),
                ('target_title', models.CharField(blank=True, max_length=400)),
                ('match_confidence', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('uncertain', 'Uncertain'), ('not_found', 'Not found'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('user_feedback', models.CharField(blank=True, max_length=20)),
                ('alternatives', models.JSONField(blank=True, default=list)),
                ('rejected_ids', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mirror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_candidates', to='api.mirrorsync')),
                ('source_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.mirrorsyncmember')),
                ('target_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.mirrorsyncmember')),
            ],
            options={
                'db_table': 'mirror_match_candidates',
                'unique_together': {('mirror', 'source_track_id', 'source_platform', 'target_member')},
            },
        ),
        migrations.CreateModel(
            name='MirrorSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_type', models.CharField(choices=[('analyze', 'Analyze'), ('sync', 'Sync')], default='sync', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('trigger', models.CharField(choices=[('manual', 'Manual'), ('cron', 'Cron')], default='manual', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('progress', models.JSONField(blank=True, default=dict)),
                ('mirror', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='api.mirrorsync')),
            ],
            options={
                'db_table': 'mirror_sync_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MirrorSyncItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_title', models.CharField(blank=True, max_length=400)),
                ('track_artist', models.CharField(blank=True, max_length=200)),
                ('action', models.CharField(choices=[('add', 'Added'), ('match', 'Matched'), ('conflict', 'Conflict')], max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.mirrorsyncmember')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.mirrorsyncrun')),
            ],
            options={
                'db_table': 'mirror_sync_items',
            },
        ),
    ]
